name: CI
on: [push, workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Download
      run: wget -O ngrok-v3-stable-linux-amd64.zip https://bin.equinox.io/c/bNyj1mQVY4c/ngrok-v3-stable-linux-amd64.zip
    - name: Extract
      run: unzip ngrok-v3-stable-linux-amd64.zip
    - name: Auth
      run: ./ngrok authtoken $NGROK_AUTH_TOKEN
      env:
        NGROK_AUTH_TOKEN: ${{ secrets.NGROK_AUTH_TOKEN }}
    - name: Install xrdp
      run: |
        sudo apt update
        sudo apt install -y xrdp
        sudo systemctl enable xrdp
        sudo systemctl start xrdp
    - name: Set Password
      run: echo -e "P@ssw0rd!\nP@ssw0rd!" | sudo passwd $USER
    - name: Create Tunnel
      run: ./ngrok tcp 3389
